<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGxWlFlB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGxWlFlB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGxWlFlB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGxWlFlB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGxWlFlB\App_KernelDevDebugContainer([
    'container.build_hash' => 'GxWlFlB',
    'container.build_id' => '58f73de4',
    'container.build_time' => 1710695241,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGxWlFlB');
