<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default.entrypoints' => 0,

], [

0 => [
    'base' => '/build/',
    'entryPoints' => [
        'app' => [
            'js' => [
                'http://localhost:5173/build/assets/index.tsx',
            ],
        ],
    ],
    'legacy' => false,
    'metadatas' => [],
    'version' => [
        '6.4.3',
        6,
        4,
        3,
    ],
    'viteServer' => 'http://localhost:5173',
],

]];
