nelmio_api_doc:
    documentation:
        info:
            title: MyBudget API
            description: API documentation for MyBudget app
            version: 1.0.0
    areas:
        path_patterns: # an array of regexps (document only routes under /api, except /api/doc)
            - ^/api(?!/doc$)
