nelmio_api_doc:
    documentation:
        info:
            title: MyBudget API
            description: API documentation for MyBudget app
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
                    in: header
        security:
            - Bearer: [ ]
        paths:
            /api/login_check:
                post:
                    tags:
                        - Authentication
                    summary: post login
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    properties:
                                        username:
                                            type: string
                                        password:
                                            type: string
                                    type: object
                    responses:
                        '200':
                            description: OK
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                                            refresh_token:
                                                type: string
                        '401':
                            description: Invalid credentials
                        '400':
                            description: Invalid JSON.
                    security: [ ]
    areas:
        path_patterns: # an array of regexps (document only utils under /api, except /api/doc)
            - ^/api(?!/doc$)
