image: php:8.3

cache:
  paths:
    - app/vendor/
    - tools/**/vendor

variables:
  SYMFONY_DEPRECATIONS_HELPER: weak

.before_script: &before_script
  before_script:
    - cd app

stages:
  - build
  - qa

build:
  stage: build
  script:
    - cd app
    - apt-get update
    - apt-get install -y unzip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install --no-interaction
  artifacts:
    paths:
      - app/vendor/
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

build-qa:
  stage: build
  script:
    - cd app
    - apt-get update
    - apt-get install -y unzip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - |
      cd ../tools
      for tool in "ecs" "rector" "phpstan" "phparkitect"; do
        cd $tool
        composer install --no-interaction
        cd ..
      done
      cd ../app
  artifacts:
    paths:
      - tools/**/vendor
      - /usr/local/bin/**
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

qa-ecs:
  stage: qa
  <<: *before_script
  script:
    - ../tools/ecs/vendor/bin/ecs check --clear-cache
  needs: [ "build" ]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - changes:
        - app/src/**
        - app/tests/**

qa-phpstan:
  stage: qa
  <<: *before_script
  script:
    - ../tools/phpstan/vendor/bin/phpstan analyse src --level=8 --configuration ./app/phpstan.neon --memory-limit 1G
  needs: [ "build" ]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - changes:
        - app/src/**
        - app/tests/**

phpunit:
  image: php:8.2-apache
  stage: qa
  services:
    - name: mysql:5.7
  variables:
    XDEBUG_MODE: coverage
    MYSQL_ROOT_PASSWORD: pass_test
    MYSQL_DATABASE: mybudget_test
    MYSQL_HOST: mysql
    MYSQL_USER: root
    MYSQL_PASSWORD: pass
    DATABASE_URL: 'mysql://root:pass@mysql:3306/mybudget'
  before_script:
    - apt-get update && apt-get install -y git libzip-dev mariadb-client
    - curl -sSk https://getcomposer.org/installer | php -- --disable-tls && mv composer.phar /usr/local/bin/composer
    - docker-php-ext-install mysqli pdo pdo_mysql zip
    - pecl install xdebug && docker-php-ext-enable xdebug
    - cd app
  script:
    - mysql -uroot -ppass_test -h mysql -e "SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''))"
    - vendor/bin/phpunit --coverage-text --coverage-cobertura=coverage.cobertura.xml
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.cobertura.xml
  allow_failure: false
  rules:
    - changes:
        - src/*
        - tests/*
