<?php

declare(strict_types=1);

namespace App\Shared\Api\Symfony\Validation;

/**
 * Enumeration of validation error codes for the Symfony Validator component.
 *
 * @see validators.en.php // TODO: how to provide this as bundled ?
 */
enum ValidationErrorCodeEnum: string
{
    case ERR_VALUE_SHOULD_BE_FALSE = 'ERR_VALUE_SHOULD_BE_FALSE';
    case ERR_VALUE_SHOULD_BE_TRUE = 'ERR_VALUE_SHOULD_BE_TRUE';
    case ERR_VALUE_SHOULD_BE_OF_TYPE = 'ERR_VALUE_SHOULD_BE_OF_TYPE';
    case ERR_VALUE_SHOULD_BE_BLANK = 'ERR_VALUE_SHOULD_BE_BLANK';
    case ERR_VALUE_SHOULD_BE_VALID_CHOICE = 'ERR_VALUE_SHOULD_BE_VALID_CHOICE';
    case ERR_MUST_SELECT_AT_LEAST_N_CHOICES = 'ERR_MUST_SELECT_AT_LEAST_N_CHOICES';
    case ERR_MUST_SELECT_AT_MOST_N_CHOICES = 'ERR_MUST_SELECT_AT_MOST_N_CHOICES';
    case ERR_ONE_OR_MORE_INVALID_VALUES = 'ERR_ONE_OR_MORE_INVALID_VALUES';
    case ERR_FIELD_NOT_EXPECTED = 'ERR_FIELD_NOT_EXPECTED';
    case ERR_FIELD_MISSING = 'ERR_FIELD_MISSING';
    case ERR_VALUE_NOT_VALID_DATE = 'ERR_VALUE_NOT_VALID_DATE';
    case ERR_VALUE_NOT_VALID_DATETIME = 'ERR_VALUE_NOT_VALID_DATETIME';
    case ERR_VALUE_NOT_VALID_EMAIL = 'ERR_VALUE_NOT_VALID_EMAIL';
    case ERR_FILE_NOT_FOUND = 'ERR_FILE_NOT_FOUND';
    case ERR_FILE_NOT_READABLE = 'ERR_FILE_NOT_READABLE';
    case ERR_FILE_TOO_LARGE = 'ERR_FILE_TOO_LARGE';
    case ERR_MIME_TYPE_INVALID = 'ERR_MIME_TYPE_INVALID';
    case ERR_VALUE_SHOULD_BE_LESS_THAN_OR_EQUAL_TO = 'ERR_VALUE_SHOULD_BE_LESS_THAN_OR_EQUAL_TO';
    case ERR_VALUE_TOO_LONG = 'ERR_VALUE_TOO_LONG';
    case ERR_VALUE_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO = 'ERR_VALUE_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO';
    case ERR_VALUE_TOO_SHORT = 'ERR_VALUE_TOO_SHORT';
    case ERR_VALUE_SHOULD_NOT_BE_BLANK = 'ERR_VALUE_SHOULD_NOT_BE_BLANK';
    case ERR_VALUE_SHOULD_NOT_BE_NULL = 'ERR_VALUE_SHOULD_NOT_BE_NULL';
    case ERR_VALUE_SHOULD_BE_NULL = 'ERR_VALUE_SHOULD_BE_NULL';
    case ERR_VALUE_NOT_VALID = 'ERR_VALUE_NOT_VALID';
    case ERR_VALUE_NOT_VALID_TIME = 'ERR_VALUE_NOT_VALID_TIME';
    case ERR_VALUE_NOT_VALID_URL = 'ERR_VALUE_NOT_VALID_URL';
    case ERR_TWO_VALUES_SHOULD_BE_EQUAL = 'ERR_TWO_VALUES_SHOULD_BE_EQUAL';
    case ERR_FILE_COULD_NOT_BE_UPLOADED = 'ERR_FILE_COULD_NOT_BE_UPLOADED';
    case ERR_VALUE_SHOULD_BE_A_VALID_NUMBER = 'ERR_VALUE_SHOULD_BE_A_VALID_NUMBER';
    case ERR_FILE_IS_NOT_A_VALID_IMAGE = 'ERR_FILE_IS_NOT_A_VALID_IMAGE';
    case ERR_VALUE_IS_NOT_A_VALID_IP_ADDRESS = 'ERR_VALUE_IS_NOT_A_VALID_IP_ADDRESS';
    case ERR_VALUE_IS_NOT_A_VALID_LANGUAGE = 'ERR_VALUE_IS_NOT_A_VALID_LANGUAGE';
    case ERR_VALUE_IS_NOT_A_VALID_LOCALE = 'ERR_VALUE_IS_NOT_A_VALID_LOCALE';
    case ERR_VALUE_IS_NOT_A_VALID_COUNTRY = 'ERR_VALUE_IS_NOT_A_VALID_COUNTRY';
    case ERR_RESOURCE_MUST_BE_UNIQUE = 'ERR_RESOURCE_MUST_BE_UNIQUE';
    case ERR_IMAGE_SIZE_COULD_NOT_BE_DETECTED = 'ERR_IMAGE_SIZE_COULD_NOT_BE_DETECTED';
    case ERR_IMAGE_WIDTH_TOO_BIG = 'ERR_IMAGE_WIDTH_TOO_BIG';
    case ERR_IMAGE_WIDTH_TOO_SMALL = 'ERR_IMAGE_WIDTH_TOO_SMALL';
    case ERR_IMAGE_HEIGHT_TOO_BIG = 'ERR_IMAGE_HEIGHT_TOO_BIG';
    case ERR_IMAGE_HEIGHT_TOO_SMALL = 'ERR_IMAGE_HEIGHT_TOO_SMALL';
    case ERR_VALUE_SHOULD_BE_USER_CURRENT_PASSWORD = 'ERR_VALUE_SHOULD_BE_USER_CURRENT_PASSWORD';
    case ERR_VALUE_SHOULD_HAVE_EXACTLY_N_CHARACTERS = 'ERR_VALUE_SHOULD_HAVE_EXACTLY_N_CHARACTERS';
    case ERR_FILE_WAS_ONLY_PARTIALLY_UPLOADED = 'ERR_FILE_WAS_ONLY_PARTIALLY_UPLOADED';
    case ERR_NO_FILE_WAS_UPLOADED = 'ERR_NO_FILE_WAS_UPLOADED';
    case ERR_NO_TEMPORARY_FOLDER_CONFIGURED_IN_PHP_INI = 'ERR_NO_TEMPORARY_FOLDER_CONFIGURED_IN_PHP_INI';
    case ERR_CANNOT_WRITE_TEMPORARY_FILE_TO_DISK = 'ERR_CANNOT_WRITE_TEMPORARY_FILE_TO_DISK';
    case ERR_PHP_EXTENSION_CAUSED_THE_UPLOAD_TO_FAIL = 'ERR_PHP_EXTENSION_CAUSED_THE_UPLOAD_TO_FAIL';
    case ERR_COLLECTION_SHOULD_CONTAIN_N_OR_MORE_ELEMENTS = 'ERR_COLLECTION_SHOULD_CONTAIN_N_OR_MORE_ELEMENTS';
    case ERR_COLLECTION_SHOULD_CONTAIN_N_OR_LESS_ELEMENTS = 'ERR_COLLECTION_SHOULD_CONTAIN_N_OR_LESS_ELEMENTS';
    case ERR_COLLECTION_SHOULD_CONTAIN_EXACTLY_N_ELEMENTS = 'ERR_COLLECTION_SHOULD_CONTAIN_EXACTLY_N_ELEMENTS';
    case ERR_INVALID_CARD_NUMBER = 'ERR_INVALID_CARD_NUMBER';
    case ERR_UNSUPPORTED_CARD_TYPE_OR_INVALID_CARD_NUMBER = 'ERR_UNSUPPORTED_CARD_TYPE_OR_INVALID_CARD_NUMBER';
    case ERR_VALUE_IS_NOT_A_VALID_IBAN = 'ERR_VALUE_IS_NOT_A_VALID_IBAN';
    case ERR_VALUE_IS_NOT_A_VALID_ISBN_10 = 'ERR_VALUE_IS_NOT_A_VALID_ISBN_10';
    case ERR_VALUE_IS_NOT_A_VALID_ISBN_13 = 'ERR_VALUE_IS_NOT_A_VALID_ISBN_13';
    case ERR_VALUE_IS_NEITHER_A_VALID_ISBN_10_NOR_A_VALID_ISBN_13 = 'ERR_VALUE_IS_NEITHER_A_VALID_ISBN_10_NOR_A_VALID_ISBN_13';
    case ERR_VALUE_IS_NOT_A_VALID_ISSN = 'ERR_VALUE_IS_NOT_A_VALID_ISSN';
    case ERR_VALUE_IS_NOT_A_VALID_CURRENCY = 'ERR_VALUE_IS_NOT_A_VALID_CURRENCY';
    case ERR_VALUE_SHOULD_BE_EQUAL_TO = 'ERR_VALUE_SHOULD_BE_EQUAL_TO';
    case ERR_VALUE_SHOULD_BE_GREATER_THAN = 'ERR_VALUE_SHOULD_BE_GREATER_THAN';
    case ERR_VALUE_SHOULD_BE_IDENTICAL_TO = 'ERR_VALUE_SHOULD_BE_IDENTICAL_TO';
    case ERR_VALUE_SHOULD_BE_LESS_THAN = 'ERR_VALUE_SHOULD_BE_LESS_THAN';
    case ERR_VALUE_SHOULD_NOT_BE_EQUAL_TO = 'ERR_VALUE_SHOULD_NOT_BE_EQUAL_TO';
    case ERR_VALUE_SHOULD_NOT_BE_IDENTICAL_TO = 'ERR_VALUE_SHOULD_NOT_BE_IDENTICAL_TO';
    case ERR_IMAGE_RATIO_TOO_BIG = 'ERR_IMAGE_RATIO_TOO_BIG';
    case ERR_IMAGE_RATIO_TOO_SMALL = 'ERR_IMAGE_RATIO_TOO_SMALL';
    case ERR_IMAGE_IS_SQUARE = 'ERR_IMAGE_IS_SQUARE';
    case ERR_IMAGE_IS_LANDSCAPE = 'ERR_IMAGE_IS_LANDSCAPE';
    case ERR_IMAGE_IS_PORTRAIT = 'ERR_IMAGE_IS_PORTRAIT';
    case ERR_EMPTY_FILE_NOT_ALLOWED = 'ERR_EMPTY_FILE_NOT_ALLOWED';
    case ERR_HOST_COULD_NOT_BE_RESOLVED = 'ERR_HOST_COULD_NOT_BE_RESOLVED';
    case ERR_VALUE_DOES_NOT_MATCH_THE_EXPECTED_CHARSET = 'ERR_VALUE_DOES_NOT_MATCH_THE_EXPECTED_CHARSET';
    case ERR_VALUE_IS_NOT_A_VALID_BIC = 'ERR_VALUE_IS_NOT_A_VALID_BIC';
    case ERR_ERROR = 'ERR_ERROR';
    case ERR_VALUE_IS_NOT_A_VALID_UUID = 'ERR_VALUE_IS_NOT_A_VALID_UUID';
    case ERR_VALUE_SHOULD_BE_A_MULTIPLE_OF = 'ERR_VALUE_SHOULD_BE_A_MULTIPLE_OF';
    case ERR_BIC_NOT_ASSOCIATED_WITH_IBAN = 'ERR_BIC_NOT_ASSOCIATED_WITH_IBAN';
    case ERR_VALUE_SHOULD_BE_VALID_JSON = 'ERR_VALUE_SHOULD_BE_VALID_JSON';
    case ERR_COLLECTION_SHOULD_CONTAIN_ONLY_UNIQUE_ELEMENTS = 'ERR_COLLECTION_SHOULD_CONTAIN_ONLY_UNIQUE_ELEMENTS';
    case ERR_VALUE_SHOULD_BE_POSITIVE = 'ERR_VALUE_SHOULD_BE_POSITIVE';
    case ERR_VALUE_SHOULD_BE_EITHER_POSITIVE_OR_ZERO = 'ERR_VALUE_SHOULD_BE_EITHER_POSITIVE_OR_ZERO';
    case ERR_VALUE_SHOULD_BE_NEGATIVE = 'ERR_VALUE_SHOULD_BE_NEGATIVE';
    case ERR_VALUE_SHOULD_BE_EITHER_NEGATIVE_OR_ZERO = 'ERR_VALUE_SHOULD_BE_EITHER_NEGATIVE_OR_ZERO';
    case ERR_VALUE_IS_NOT_A_VALID_TIMEZONE = 'ERR_VALUE_IS_NOT_A_VALID_TIMEZONE';
    case ERR_PASSWORD_LEAKED = 'ERR_PASSWORD_LEAKED';
    case ERR_VALUE_SHOULD_BE_BETWEEN = 'ERR_VALUE_SHOULD_BE_BETWEEN';
    case ERR_VALUE_IS_NOT_A_VALID_HOSTNAME = 'ERR_VALUE_IS_NOT_A_VALID_HOSTNAME';
    case ERR_NUMBER_OF_ELEMENTS_SHOULD_BE_A_MULTIPLE_OF = 'ERR_NUMBER_OF_ELEMENTS_SHOULD_BE_A_MULTIPLE_OF';
    case ERR_VALUE_SHOULD_SATISFY_AT_LEAST_ONE_OF_THE_FOLLOWING_CONSTRAINTS = 'ERR_VALUE_SHOULD_SATISFY_AT_LEAST_ONE_OF_THE_FOLLOWING_CONSTRAINTS';
    case ERR_EACH_ELEMENT_OF_THIS_COLLECTION_SHOULD_SATISFY_ITS_OWN_SET_OF_CONSTRAINTS = 'ERR_EACH_ELEMENT_OF_THIS_COLLECTION_SHOULD_SATISFY_ITS_OWN_SET_OF_CONSTRAINTS';
    case ERR_VALUE_IS_NOT_A_VALID_ISIN = 'ERR_VALUE_IS_NOT_A_VALID_ISIN';
    case ERR_VALUE_SHOULD_BE_A_VALID_EXPRESSION = 'ERR_VALUE_SHOULD_BE_A_VALID_EXPRESSION';
    case ERR_VALUE_IS_NOT_A_VALID_CSS_COLOR = 'ERR_VALUE_IS_NOT_A_VALID_CSS_COLOR';
    case ERR_VALUE_IS_NOT_A_VALID_CIDR = 'ERR_VALUE_IS_NOT_A_VALID_CIDR';
    case ERR_VALUE_OF_THE_NETMASK_SHOULD_BE_BETWEEN = 'ERR_VALUE_OF_THE_NETMASK_SHOULD_BE_BETWEEN';
    case ERR_FILENAME_IS_TOO_LONG = 'ERR_FILENAME_IS_TOO_LONG';
    case ERR_PASSWORD_STRENGTH_TOO_LOW = 'ERR_PASSWORD_STRENGTH_TOO_LOW';
    case ERR_VALUE_CONTAINS_CHARACTERS_THAT_ARE_NOT_ALLOWED_BY_THE_CURRENT_RESTRICTION_LEVEL = 'ERR_VALUE_CONTAINS_CHARACTERS_THAT_ARE_NOT_ALLOWED_BY_THE_CURRENT_RESTRICTION_LEVEL';
    case ERR_USING_INVISIBLE_CHARACTERS_IS_NOT_ALLOWED = 'ERR_USING_INVISIBLE_CHARACTERS_IS_NOT_ALLOWED';
    case ERR_MIXING_NUMBERS_FROM_DIFFERENT_SCRIPTS_IS_NOT_ALLOWED = 'ERR_MIXING_NUMBERS_FROM_DIFFERENT_SCRIPTS_IS_NOT_ALLOWED';
    case ERR_USING_HIDDEN_OVERLAY_CHARACTERS_IS_NOT_ALLOWED = 'ERR_USING_HIDDEN_OVERLAY_CHARACTERS_IS_NOT_ALLOWED';
}
