/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MyBudget API
 * API for budget and savings management
 * OpenAPI spec version: 1.0.0
 */

/**
 * Account partial data
 */
export interface AccountPartialResponse {
  /** Account identifier */
  id: number
  /** Account name */
  name: string
}
