/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * MyBudget API
 * API for budget and savings management
 * OpenAPI spec version: 1.0.0
 */
import type { AccountPartialResponse } from './accountPartialResponse'
import type { BalanceResponse } from './balanceResponse'

/**
 * Balance history data
 */
export interface BalanceHistoryResponse {
  /** List of accounts */
  accounts: AccountPartialResponse[]
  /** List of balances by date */
  balances: BalanceResponse[]
}
