/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MyBudget API
 * API for budget and savings management
 * OpenAPI spec version: 1.0.0
 */

/**
 * Balance data
 */
export interface BalanceResponse {
  /** Balance date (YYYY-MM-DD) */
  date: string
  /** Formatted date */
  formattedDate: string
  /** Balance amount */
  balance: number
}
