/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MyBudget API
 * API for budget and savings management
 * OpenAPI spec version: 1.0.0
 */
import type { IncomePayload } from './incomePayload'
import type { ExpensePayload } from './expensePayload'

/**
 * Data for creating or updating a budget
 */
export interface BudgetPayload {
  /** Budget date (YYYY-MM-DD) */
  date: Date
  /** List of incomes */
  incomes: IncomePayload[]
  /** List of expenses */
  expenses: ExpensePayload[]
}
