/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * MyBudget API
 * API for budget and savings management
 * OpenAPI spec version: 1.0.0
 */
import type { IncomeResponse } from './incomeResponse'
import type { ExpenseResponse } from './expenseResponse'

/**
 * Budget data
 */
export interface BudgetResponse {
  /** Unique budget identifier */
  id: number
  /** Budget name */
  name: string
  /** Total income amount */
  incomesAmount: number
  /** Total expenses amount */
  expensesAmount: number
  /** Saving capacity */
  savingCapacity: number
  /** Budget date (YYYY-MM) */
  date: string
  /** List of incomes */
  incomes: IncomeResponse[]
  /** List of expenses */
  expenses: ExpenseResponse[]
}
