/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * MyBudget API
 * API for budget and savings management
 * OpenAPI spec version: 1.0.0
 */

/**
 * Expense data
 */
export interface ExpenseResponse {
  /** Unique expense identifier */
  id: number
  /** Expense name */
  name: string
  /** Expense amount */
  amount: number
  /** Expense category */
  category: string
}
