/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * MyBudget API
 * API for budget and savings management
 * OpenAPI spec version: 1.0.0
 */

/**
 * Data for creating or updating an expense
 */
export interface ExpensePayload {
  /** Expense name */
  name: string
  /** Expense amount */
  amount: number
  /** Expense category */
  category: string
}
