/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MyBudget API
 * API for budget and savings management
 * OpenAPI spec version: 1.0.0
 */

export type GetApiTransactionsList200Meta = {
  total?: number
  currentPage?: number
  perPage?: number
  from?: number
  to?: number
  hasMore?: boolean
}
