/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MyBudget API
 * API for budget and savings management
 * OpenAPI spec version: 1.0.0
 */
import type { UserResponse } from './userResponse'

export type GetApiUsersGet200 = {
  data?: UserResponse
}
