/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MyBudget API
 * API for budget and savings management
 * OpenAPI spec version: 1.0.0
 */
import type { TransactionResponse } from './transactionResponse'
import type { GetApiTransactionsList200Meta } from './getApiTransactionsList200Meta'

export type GetApiTransactionsList200 = {
  data?: TransactionResponse[]
  meta?: GetApiTransactionsList200Meta
}
