/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * MyBudget API
 * API for budget and savings management
 * OpenAPI spec version: 1.0.0
 */
import type { AccountResponse } from './accountResponse'

export type GetApiAccountsGet200 = {
  data?: AccountResponse
}
