/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * MyBudget API
 * API for budget and savings management
 * OpenAPI spec version: 1.0.0
 */
import type { BudgetResponse } from './budgetResponse'
import type { GetApiBudgetsList200Meta } from './getApiBudgetsList200Meta'

export type GetApiBudgetsList200 = {
  data?: BudgetResponse[]
  meta?: GetApiBudgetsList200Meta
}
