/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MyBudget API
 * API for budget and savings management
 * OpenAPI spec version: 1.0.0
 */

/**
 * Data for creating or updating an income
 */
export interface IncomePayload {
  /** Income name */
  name: string
  /** Income amount */
  amount: number
}
