/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MyBudget API
 * API for budget and savings management
 * OpenAPI spec version: 1.0.0
 */

/**
 * Income data
 */
export interface IncomeResponse {
  /** Unique income identifier */
  id: number
  /** Income name */
  name: string
  /** Income amount */
  amount: number
}
