/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * MyBudget API
 * API for budget and savings management
 * OpenAPI spec version: 1.0.0
 */

export type PeriodsEnum = (typeof PeriodsEnum)[keyof typeof PeriodsEnum]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PeriodsEnum = {
  NUMBER_6: '6',
  NUMBER_12: '12',
  NUMBER_24: '24',
} as const
