/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MyBudget API
 * API for budget and savings management
 * OpenAPI spec version: 1.0.0
 */
import type { BudgetResponse } from './budgetResponse'

export type PostApiBudgetsCreate201 = {
  data?: BudgetResponse
}
