/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * MyBudget API
 * API for budget and savings management
 * OpenAPI spec version: 1.0.0
 */
import type { TransactionResponse } from './transactionResponse'

export type PutApiTransactionUpdate200 = {
  data?: TransactionResponse
}
