/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MyBudget API
 * API for budget and savings management
 * OpenAPI spec version: 1.0.0
 */

/**
 * User registration data
 */
export interface RegisterPayload {
  /** User email */
  email: string
  /** User first name */
  firstName: string
  /** User last name */
  lastName: string
  /** User password */
  password: string
}
