/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * MyBudget API
 * API for budget and savings management
 * OpenAPI spec version: 1.0.0
 */

/**
 * Transaction type
 */
export type TransactionResponseType =
  (typeof TransactionResponseType)[keyof typeof TransactionResponseType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionResponseType = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
} as const
