/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * MyBudget API
 * API for budget and savings management
 * OpenAPI spec version: 1.0.0
 */
import type { TransactionResponseType } from './transactionResponseType'
import type { AccountPartialResponse } from './accountPartialResponse'

/**
 * Transaction data
 */
export interface TransactionResponse {
  /** Transaction identifier */
  id: number
  /** Transaction description */
  description: string
  /** Transaction amount */
  amount: number
  /** Transaction type */
  type: TransactionResponseType
  /** Transaction date */
  date: Date
  account: AccountPartialResponse
}
