/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * MyBudget API
 * API for budget and savings management
 * OpenAPI spec version: 1.0.0
 */

/**
 * Transaction type
 */
export type TransactionPayloadType =
  (typeof TransactionPayloadType)[keyof typeof TransactionPayloadType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionPayloadType = {
  DEBIT: 'DEBIT',
  CREDIT: 'CREDIT',
} as const
