/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * MyBudget API
 * API for budget and savings management
 * OpenAPI spec version: 1.0.0
 */

/**
 * User data
 */
export interface UserResponse {
  /** User identifier */
  id: number
  /** User email */
  email: string
  /** User first name */
  firstName: string
  /** User last name */
  lastName: string
}
