accounts_controllers:
  resource:
    path: ../src/Account/Controller/
    namespace: App\Account\Controller
  type: attribute
  format: json
  prefix: /api

transactions_controllers:
  resource:
    path: ../src/Transaction/Controller/
    namespace: App\Transaction\Controller
  type: attribute
  format: json
  prefix: /api

user_controllers:
  resource:
    path: ../src/User/Controller/
    namespace: App\User\Controller
  type: attribute
  format: json
  prefix: /api

budgets_controllers:
  resource:
    path: ../src/Budget/Controller/
    namespace: App\Budget\Controller
  type: attribute
  format: json
  prefix: /api

savings_controllers:
  resource:
    path: ../src/Savings/Controller/
    namespace: App\Savings\Controller
  type: attribute
  format: json
  prefix: /api

api.swagger_ui:
  path: /api/docs
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

api_login_check:
  path: /api/login

app_default:
  path: /{path?}
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: base.html.twig
  requirements:
    path: '^(?!api/).*$'
