controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
  format: json
  prefix: /api

api.swagger_ui:
  path: /api/docs
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

api_login_check:
  path: /api/login

app_default:
  path: /{path?}
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: base.html.twig
  requirements:
    path: "^(?!api/).*$"
