budgets_controllers:
  resource:
    path: ../src/Budget/Controller/
    namespace: App\Budget\Controller
  type: attribute
  format: json
  prefix: /api

savings_controllers:
  resource:
    path: ../src/Savings/Controller/
    namespace: App\Savings\Controller
  type: attribute
  format: json
  prefix: /api

shared_controllers:
  resource:
    path: ../src/Shared/Controller/
    namespace: App\Shared\Controller
  type: attribute
  format: json
  prefix: /api

api_login_check:
  path: /api/login

app_default:
  path: /{path?}
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: base.html.twig
  requirements:
    path: "^(?!api/).*$"