<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLgw3NR0\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLgw3NR0/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerLgw3NR0.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerLgw3NR0\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerLgw3NR0\App_KernelTestDebugContainer([
    'container.build_hash' => 'Lgw3NR0',
    'container.build_id' => '2398f772',
    'container.build_time' => 1710699202,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLgw3NR0');
