<?php

namespace ContainerGxWlFlB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WfIByAiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WfIByAi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WfIByAi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'expense' => ['privates', '.errored..service_locator.WfIByAi.App\\Entity\\Expense', NULL, 'Cannot autowire service ".service_locator.WfIByAi": it needs an instance of "App\\Entity\\Expense" but this type has been excluded in "config/services.yaml".'],
            'expenseService' => ['privates', 'App\\Service\\ExpenseService', 'getExpenseServiceService', true],
        ], [
            'expense' => 'App\\Entity\\Expense',
            'expenseService' => 'App\\Service\\ExpenseService',
        ]);
    }
}
