<?php

namespace ContainerGxWlFlB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U9xLpfvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u9xLpfv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u9xLpfv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'incomePayload' => ['privates', 'App\\Dto\\Income\\Payload\\IncomePayload', 'getIncomePayloadService', true],
            'incomeService' => ['privates', 'App\\Service\\IncomeService', 'getIncomeServiceService', true],
        ], [
            'incomePayload' => 'App\\Dto\\Income\\Payload\\IncomePayload',
            'incomeService' => 'App\\Service\\IncomeService',
        ]);
    }
}
