<?php

namespace ContainerGxWlFlB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E_Rk27rService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e.rk27r' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.e.rk27r'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'income' => ['privates', '.errored..service_locator.e.rk27r.App\\Entity\\Income', NULL, 'Cannot autowire service ".service_locator.e.rk27r": it needs an instance of "App\\Entity\\Income" but this type has been excluded in "config/services.yaml".'],
            'incomeService' => ['privates', 'App\\Service\\IncomeService', 'getIncomeServiceService', true],
        ], [
            'income' => 'App\\Entity\\Income',
            'incomeService' => 'App\\Service\\IncomeService',
        ]);
    }
}
