<?php

namespace ContainerGxWlFlB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EC5lAdzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eC5lAdz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eC5lAdz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'context' => ['privates', '.errored..service_locator.eC5lAdz.Symfony\\Component\\Serializer\\Context\\Normalizer\\ObjectNormalizerContextBuilder', NULL, 'Cannot autowire service ".service_locator.eC5lAdz": it references class "Symfony\\Component\\Serializer\\Context\\Normalizer\\ObjectNormalizerContextBuilder" but no such service exists.'],
        ], [
            'context' => 'Symfony\\Component\\Serializer\\Context\\Normalizer\\ObjectNormalizerContextBuilder',
        ]);
    }
}
