<?php

namespace ContainerGxWlFlB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EvFcme2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.evFcme2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.evFcme2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'expensePayload' => ['privates', 'App\\Dto\\Expense\\Payload\\ExpensePayload', 'getExpensePayloadService', true],
            'expenseService' => ['privates', 'App\\Service\\ExpenseService', 'getExpenseServiceService', true],
        ], [
            'expensePayload' => 'App\\Dto\\Expense\\Payload\\ExpensePayload',
            'expenseService' => 'App\\Service\\ExpenseService',
        ]);
    }
}
