<?php

namespace ContainerGxWlFlB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QI1oTZbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qI1oTZb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qI1oTZb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'expenseCategory' => ['privates', '.errored..service_locator.qI1oTZb.App\\Entity\\ExpenseCategory', NULL, 'Cannot autowire service ".service_locator.qI1oTZb": it needs an instance of "App\\Entity\\ExpenseCategory" but this type has been excluded in "config/services.yaml".'],
            'expenseCategoryPayload' => ['privates', 'App\\Dto\\ExpenseCategory\\Payload\\ExpenseCategoryPayload', 'getExpenseCategoryPayloadService', true],
            'expenseCategoryService' => ['privates', 'App\\Service\\ExpenseCategoryService', 'getExpenseCategoryServiceService', true],
        ], [
            'expenseCategory' => 'App\\Entity\\ExpenseCategory',
            'expenseCategoryPayload' => 'App\\Dto\\ExpenseCategory\\Payload\\ExpenseCategoryPayload',
            'expenseCategoryService' => 'App\\Service\\ExpenseCategoryService',
        ]);
    }
}
