<?php

namespace ContainerGxWlFlB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExpenseCategoryPayloadService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Dto\ExpenseCategory\Payload\ExpenseCategoryPayload' shared autowired service.
     *
     * @return \App\Dto\ExpenseCategory\Payload\ExpenseCategoryPayload
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/dcorroyer/my-rest-bundle/src/Contract/PayloadInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Trait/Payload/IdPayloadTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Trait/Payload/NamePayloadTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Dto/ExpenseCategory/Payload/ExpenseCategoryPayload.php';

        return $container->privates['App\\Dto\\ExpenseCategory\\Payload\\ExpenseCategoryPayload'] = new \App\Dto\ExpenseCategory\Payload\ExpenseCategoryPayload();
    }
}
