<?php

namespace ContainerGxWlFlB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateEndpointTestCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\GenerateEndpointTestCommand' shared autowired service.
     *
     * @return \App\Command\GenerateEndpointTestCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/GenerateEndpointTestCommand.php';

        $container->privates['App\\Command\\GenerateEndpointTestCommand'] = $instance = new \App\Command\GenerateEndpointTestCommand(($container->services['router'] ?? self::getRouterService($container)));

        $instance->setName('make:endpoint:test');
        $instance->setAliases(['met']);
        $instance->setDescription('Generate a endpoint test');

        return $instance;
    }
}
