<?php

namespace ContainerGxWlFlB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateEndpointTestCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\GenerateEndpointTestCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\GenerateEndpointTestCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('make:endpoint:test', ['met'], 'Generate a endpoint test', false, #[\Closure(name: 'App\\Command\\GenerateEndpointTestCommand')] fn (): \App\Command\GenerateEndpointTestCommand => ($container->privates['App\\Command\\GenerateEndpointTestCommand'] ?? $container->load('getGenerateEndpointTestCommandService')));
    }
}
