<?php

namespace ContainerGxWlFlB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIncomeFilterQueryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Dto\Income\Http\IncomeFilterQuery' shared autowired service.
     *
     * @return \App\Dto\Income\Http\IncomeFilterQuery
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/dcorroyer/my-rest-bundle/src/Contract/QueryFilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/dcorroyer/my-rest-bundle/src/Contract/ORMFilterInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Dto/Income/Http/IncomeFilterQuery.php';

        return $container->privates['App\\Dto\\Income\\Http\\IncomeFilterQuery'] = new \App\Dto\Income\Http\IncomeFilterQuery();
    }
}
