<?php

namespace ContainerGxWlFlB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListTrackingControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Tracking\ListTrackingController' shared autowired service.
     *
     * @return \App\Controller\Tracking\ListTrackingController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/dcorroyer/my-rest-bundle/src/Controller/BaseRestController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Tracking/ListTrackingController.php';

        $container->services['App\\Controller\\Tracking\\ListTrackingController'] = $instance = new \App\Controller\Tracking\ListTrackingController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Tracking\\ListTrackingController', $container));

        return $instance;
    }
}
