<?php

namespace ContainerGxWlFlB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSlidingPaginationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.qfxC2nW.Knp\Bundle\PaginatorBundle\Pagination\SlidingPagination' shared service.
     *
     * @return \Knp\Bundle\PaginatorBundle\Pagination\SlidingPagination
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.qfxC2nW": it references class "Knp\\Bundle\\PaginatorBundle\\Pagination\\SlidingPagination" but no such service exists.');
    }
}
