<?php

namespace ContainerGxWlFlB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTracking2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.h_8Awd8.App\Entity\Tracking' shared service.
     *
     * @return \App\Entity\Tracking
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.h_8Awd8": it needs an instance of "App\\Entity\\Tracking" but this type has been excluded in "config/services.yaml".');
    }
}
