<?php

namespace ContainerGxWlFlB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateTrackingPayloadService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Dto\Tracking\Payload\UpdateTrackingPayload' shared autowired service.
     *
     * @return \App\Dto\Tracking\Payload\UpdateTrackingPayload
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/dcorroyer/my-rest-bundle/src/Contract/PayloadInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Trait/Payload/DatePayloadTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Dto/Tracking/Payload/UpdateTrackingPayload.php';

        return $container->privates['App\\Dto\\Tracking\\Payload\\UpdateTrackingPayload'] = new \App\Dto\Tracking\Payload\UpdateTrackingPayload();
    }
}
