<?php

namespace ContainerLgw3NR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GP1DvfTService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.GP1DvfT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GP1DvfT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'expenseCategory' => ['privates', '.errored..service_locator.GP1DvfT.App\\Entity\\ExpenseCategory', NULL, 'Cannot autowire service ".service_locator.GP1DvfT": it needs an instance of "App\\Entity\\ExpenseCategory" but this type has been excluded in "config/services.yaml".'],
        ], [
            'expenseCategory' => 'App\\Entity\\ExpenseCategory',
        ]);
    }
}
