<?php

namespace ContainerLgw3NR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QfxC2nWService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.qfxC2nW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qfxC2nW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pagination' => ['privates', '.errored..service_locator.qfxC2nW.Knp\\Bundle\\PaginatorBundle\\Pagination\\SlidingPagination', NULL, 'Cannot autowire service ".service_locator.qfxC2nW": it references class "Knp\\Bundle\\PaginatorBundle\\Pagination\\SlidingPagination" but no such service exists.'],
        ], [
            'pagination' => 'Knp\\Bundle\\PaginatorBundle\\Pagination\\SlidingPagination',
        ]);
    }
}
