<?php

namespace ContainerLgw3NR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DRDVPeJService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.DRDVPeJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DRDVPeJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'expenseCategoryService' => ['privates', 'App\\Service\\ExpenseCategoryService', 'getExpenseCategoryServiceService', true],
            'filter' => ['privates', 'App\\Dto\\ExpenseCategory\\Http\\ExpenseCategoryFilterQuery', 'getExpenseCategoryFilterQueryService', true],
            'paginationQueryParams' => ['privates', 'My\\RestBundle\\Dto\\PaginationQueryParams', 'getPaginationQueryParamsService', true],
        ], [
            'expenseCategoryService' => 'App\\Service\\ExpenseCategoryService',
            'filter' => 'App\\Dto\\ExpenseCategory\\Http\\ExpenseCategoryFilterQuery',
            'paginationQueryParams' => 'My\\RestBundle\\Dto\\PaginationQueryParams',
        ]);
    }
}
