<?php

namespace ContainerLgw3NR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FRKLixSService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.FRKLixS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FRKLixS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'income' => ['privates', '.errored..service_locator.FRKLixS.App\\Entity\\Income', NULL, 'Cannot autowire service ".service_locator.FRKLixS": it needs an instance of "App\\Entity\\Income" but this type has been excluded in "config/services.yaml".'],
            'incomePayload' => ['privates', 'App\\Dto\\Income\\Payload\\IncomePayload', 'getIncomePayloadService', true],
            'incomeService' => ['privates', 'App\\Service\\IncomeService', 'getIncomeServiceService', true],
        ], [
            'income' => 'App\\Entity\\Income',
            'incomePayload' => 'App\\Dto\\Income\\Payload\\IncomePayload',
            'incomeService' => 'App\\Service\\IncomeService',
        ]);
    }
}
