<?php

namespace ContainerLgw3NR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_McEQHJ4Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.McEQHJ4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.McEQHJ4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'expenseService' => ['privates', 'App\\Service\\ExpenseService', 'getExpenseServiceService', true],
            'filter' => ['privates', 'App\\Dto\\Expense\\Http\\ExpenseFilterQuery', 'getExpenseFilterQueryService', true],
            'paginationQueryParams' => ['privates', 'My\\RestBundle\\Dto\\PaginationQueryParams', 'getPaginationQueryParamsService', true],
        ], [
            'expenseService' => 'App\\Service\\ExpenseService',
            'filter' => 'App\\Dto\\Expense\\Http\\ExpenseFilterQuery',
            'paginationQueryParams' => 'My\\RestBundle\\Dto\\PaginationQueryParams',
        ]);
    }
}
