<?php

namespace ContainerLgw3NR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BH5pAteService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.bH5pAte' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bH5pAte'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'trackingService' => ['privates', 'App\\Service\\TrackingService', 'getTrackingServiceService', true],
        ], [
            'trackingService' => 'App\\Service\\TrackingService',
        ]);
    }
}
