<?php

namespace ContainerLgw3NR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BPAXT1mService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.bPAXT1m' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bPAXT1m'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'expense' => ['privates', '.errored..service_locator.bPAXT1m.App\\Entity\\Expense', NULL, 'Cannot autowire service ".service_locator.bPAXT1m": it needs an instance of "App\\Entity\\Expense" but this type has been excluded in "config/services.yaml".'],
        ], [
            'expense' => 'App\\Entity\\Expense',
        ]);
    }
}
