<?php

namespace ContainerLgw3NR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C2nDQFmService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.c2nDQFm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.c2nDQFm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'filter' => ['privates', 'App\\Dto\\Income\\Http\\IncomeFilterQuery', 'getIncomeFilterQueryService', true],
            'incomeService' => ['privates', 'App\\Service\\IncomeService', 'getIncomeServiceService', true],
            'paginationQueryParams' => ['privates', 'My\\RestBundle\\Dto\\PaginationQueryParams', 'getPaginationQueryParamsService', true],
        ], [
            'filter' => 'App\\Dto\\Income\\Http\\IncomeFilterQuery',
            'incomeService' => 'App\\Service\\IncomeService',
            'paginationQueryParams' => 'My\\RestBundle\\Dto\\PaginationQueryParams',
        ]);
    }
}
