<?php

namespace ContainerLgw3NR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5wU_2LVService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.5wU.2LV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5wU.2LV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'payload' => ['privates', 'App\\Dto\\User\\Payload\\RegisterPayload', 'getRegisterPayloadService', true],
            'userService' => ['privates', 'App\\Service\\UserService', 'getUserServiceService', true],
        ], [
            'payload' => 'App\\Dto\\User\\Payload\\RegisterPayload',
            'userService' => 'App\\Service\\UserService',
        ]);
    }
}
