<?php

namespace ContainerLgw3NR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H8Awd8Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.h_8Awd8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.h_8Awd8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tracking' => ['privates', '.errored..service_locator.h_8Awd8.App\\Entity\\Tracking', NULL, 'Cannot autowire service ".service_locator.h_8Awd8": it needs an instance of "App\\Entity\\Tracking" but this type has been excluded in "config/services.yaml".'],
            'trackingService' => ['privates', 'App\\Service\\TrackingService', 'getTrackingServiceService', true],
        ], [
            'tracking' => 'App\\Entity\\Tracking',
            'trackingService' => 'App\\Service\\TrackingService',
        ]);
    }
}
