<?php

namespace ContainerLgw3NR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBaseRestControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'My\RestBundle\Controller\BaseRestController' shared autowired service.
     *
     * @return \My\RestBundle\Controller\BaseRestController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/dcorroyer/my-rest-bundle/src/Controller/BaseRestController.php';

        $container->services['My\\RestBundle\\Controller\\BaseRestController'] = $instance = new \My\RestBundle\Controller\BaseRestController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('My\\RestBundle\\Controller\\BaseRestController', $container));

        return $instance;
    }
}
