<?php

namespace ContainerLgw3NR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDtoToEntityHelperService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'My\RestBundle\Helper\DtoToEntityHelper' shared autowired service.
     *
     * @return \My\RestBundle\Helper\DtoToEntityHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/dcorroyer/my-rest-bundle/src/Helper/DtoToEntityHelper.php';

        $a = ($container->privates['serializer'] ?? self::getSerializerService($container));

        if (isset($container->privates['My\\RestBundle\\Helper\\DtoToEntityHelper'])) {
            return $container->privates['My\\RestBundle\\Helper\\DtoToEntityHelper'];
        }

        return $container->privates['My\\RestBundle\\Helper\\DtoToEntityHelper'] = new \My\RestBundle\Helper\DtoToEntityHelper($a, $a);
    }
}
