<?php

namespace ContainerLgw3NR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExpenseFilterQueryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Dto\Expense\Http\ExpenseFilterQuery' shared autowired service.
     *
     * @return \App\Dto\Expense\Http\ExpenseFilterQuery
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/dcorroyer/my-rest-bundle/src/Contract/QueryFilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/dcorroyer/my-rest-bundle/src/Contract/ORMFilterInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Dto/Expense/Http/ExpenseFilterQuery.php';

        return $container->privates['App\\Dto\\Expense\\Http\\ExpenseFilterQuery'] = new \App\Dto\Expense\Http\ExpenseFilterQuery();
    }
}
