<?php

namespace ContainerLgw3NR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExpenseCategoryServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\ExpenseCategoryService' shared autowired service.
     *
     * @return \App\Service\ExpenseCategoryService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/ExpenseCategoryService.php';

        $a = ($container->privates['App\\Repository\\ExpenseCategoryRepository'] ?? $container->load('getExpenseCategoryRepositoryService'));

        if (isset($container->privates['App\\Service\\ExpenseCategoryService'])) {
            return $container->privates['App\\Service\\ExpenseCategoryService'];
        }

        return $container->privates['App\\Service\\ExpenseCategoryService'] = new \App\Service\ExpenseCategoryService($a);
    }
}
