<?php

namespace ContainerLgw3NR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExpenseLineRepositoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Repository\ExpenseLineRepository' shared autowired service.
     *
     * @return \App\Repository\ExpenseLineRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/Persistence/ObjectRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/collections/src/Selectable.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/EntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Repository/LazyServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/dcorroyer/my-rest-bundle/src/Repository/Common/AbstractEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Repository/ExpenseLineRepository.php';

        $a = ($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService'));

        if (isset($container->privates['App\\Repository\\ExpenseLineRepository'])) {
            return $container->privates['App\\Repository\\ExpenseLineRepository'];
        }

        return $container->privates['App\\Repository\\ExpenseLineRepository'] = new \App\Repository\ExpenseLineRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)), $a);
    }
}
