<?php

namespace ContainerLgw3NR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExpensePayloadService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Dto\Expense\Payload\ExpensePayload' shared autowired service.
     *
     * @return \App\Dto\Expense\Payload\ExpensePayload
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/dcorroyer/my-rest-bundle/src/Contract/PayloadInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Dto/Expense/Payload/ExpensePayload.php';

        return $container->privates['App\\Dto\\Expense\\Payload\\ExpensePayload'] = new \App\Dto\Expense\Payload\ExpensePayload();
    }
}
