<?php

namespace ContainerLgw3NR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExpense3Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ykSUEzA.App\Entity\Expense' shared service.
     *
     * @return \App\Entity\Expense
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ykSUEzA": it needs an instance of "App\\Entity\\Expense" but this type has been excluded in "config/services.yaml".');
    }
}
