<?php

namespace ContainerLgw3NR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExpenseServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\ExpenseService' shared autowired service.
     *
     * @return \App\Service\ExpenseService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/ExpenseService.php';

        $a = ($container->privates['App\\Repository\\ExpenseRepository'] ?? $container->load('getExpenseRepositoryService'));

        if (isset($container->privates['App\\Service\\ExpenseService'])) {
            return $container->privates['App\\Service\\ExpenseService'];
        }
        $b = ($container->privates['App\\Repository\\ExpenseLineRepository'] ?? $container->load('getExpenseLineRepositoryService'));

        if (isset($container->privates['App\\Service\\ExpenseService'])) {
            return $container->privates['App\\Service\\ExpenseService'];
        }
        $c = ($container->privates['App\\Repository\\ExpenseCategoryRepository'] ?? $container->load('getExpenseCategoryRepositoryService'));

        if (isset($container->privates['App\\Service\\ExpenseService'])) {
            return $container->privates['App\\Service\\ExpenseService'];
        }
        $d = ($container->privates['App\\Service\\ExpenseCategoryService'] ?? $container->load('getExpenseCategoryServiceService'));

        if (isset($container->privates['App\\Service\\ExpenseService'])) {
            return $container->privates['App\\Service\\ExpenseService'];
        }

        return $container->privates['App\\Service\\ExpenseService'] = new \App\Service\ExpenseService($a, $b, $c, $d);
    }
}
