<?php

namespace ContainerLgw3NR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIncomePayloadService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Dto\Income\Payload\IncomePayload' shared autowired service.
     *
     * @return \App\Dto\Income\Payload\IncomePayload
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/dcorroyer/my-rest-bundle/src/Contract/PayloadInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Dto/Income/Payload/IncomePayload.php';

        return $container->privates['App\\Dto\\Income\\Payload\\IncomePayload'] = new \App\Dto\Income\Payload\IncomePayload();
    }
}
