<?php

namespace ContainerLgw3NR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIncomeServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\IncomeService' shared autowired service.
     *
     * @return \App\Service\IncomeService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/IncomeService.php';

        $a = ($container->privates['App\\Repository\\IncomeRepository'] ?? $container->load('getIncomeRepositoryService'));

        if (isset($container->privates['App\\Service\\IncomeService'])) {
            return $container->privates['App\\Service\\IncomeService'];
        }
        $b = ($container->privates['App\\Repository\\IncomeLineRepository'] ?? $container->load('getIncomeLineRepositoryService'));

        if (isset($container->privates['App\\Service\\IncomeService'])) {
            return $container->privates['App\\Service\\IncomeService'];
        }

        return $container->privates['App\\Service\\IncomeService'] = new \App\Service\IncomeService($a, $b);
    }
}
