<?php

namespace ContainerLgw3NR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKnpPaginator_Helper_ProcessorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'knp_paginator.helper.processor' shared service.
     *
     * @return \Knp\Bundle\PaginatorBundle\Helper\Processor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/knplabs/knp-paginator-bundle/src/Helper/Processor.php';

        return $container->privates['knp_paginator.helper.processor'] = new \Knp\Bundle\PaginatorBundle\Helper\Processor(($container->services['router'] ?? self::getRouterService($container)), ($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
