<?php

namespace ContainerLgw3NR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListExpenseControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\Expense\ListExpenseController' shared autowired service.
     *
     * @return \App\Controller\Expense\ListExpenseController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/dcorroyer/my-rest-bundle/src/Controller/BaseRestController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Expense/ListExpenseController.php';

        $container->services['App\\Controller\\Expense\\ListExpenseController'] = $instance = new \App\Controller\Expense\ListExpenseController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Expense\\ListExpenseController', $container));

        return $instance;
    }
}
