<?php

namespace ContainerLgw3NR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getObjectNormalizerContextBuilderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.eC5lAdz.Symfony\Component\Serializer\Context\Normalizer\ObjectNormalizerContextBuilder' shared service.
     *
     * @return \Symfony\Component\Serializer\Context\Normalizer\ObjectNormalizerContextBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.eC5lAdz": it references class "Symfony\\Component\\Serializer\\Context\\Normalizer\\ObjectNormalizerContextBuilder" but no such service exists.');
    }
}
