<?php

namespace ContainerLgw3NR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaginationQueryParamsService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'My\RestBundle\Dto\PaginationQueryParams' shared autowired service.
     *
     * @return \My\RestBundle\Dto\PaginationQueryParams
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/dcorroyer/my-rest-bundle/src/Dto/PaginationQueryParams.php';

        return $container->privates['My\\RestBundle\\Dto\\PaginationQueryParams'] = new \My\RestBundle\Dto\PaginationQueryParams();
    }
}
