<?php

namespace ContainerLgw3NR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPentatrionVite_FileAccessorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'pentatrion_vite.file_accessor' shared service.
     *
     * @return \Pentatrion\ViteBundle\Service\FileAccessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pentatrion/vite-bundle/src/Service/FileAccessor.php';

        return $container->privates['pentatrion_vite.file_accessor'] = new \Pentatrion\ViteBundle\Service\FileAccessor((\dirname(__DIR__, 4).'/public'), $container->parameters['pentatrion_vite.configs'], NULL);
    }
}
