<?php

namespace ContainerLgw3NR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrackingFilterQueryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Dto\Tracking\Http\TrackingFilterQuery' shared autowired service.
     *
     * @return \App\Dto\Tracking\Http\TrackingFilterQuery
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/dcorroyer/my-rest-bundle/src/Contract/QueryFilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/dcorroyer/my-rest-bundle/src/Contract/ORMFilterInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Dto/Tracking/Http/TrackingFilterQuery.php';

        return $container->privates['App\\Dto\\Tracking\\Http\\TrackingFilterQuery'] = new \App\Dto\Tracking\Http\TrackingFilterQuery();
    }
}
