<?php

namespace ContainerLgw3NR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrackingServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\TrackingService' shared autowired service.
     *
     * @return \App\Service\TrackingService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/TrackingService.php';

        $a = ($container->privates['App\\Repository\\TrackingRepository'] ?? $container->load('getTrackingRepositoryService'));

        if (isset($container->privates['App\\Service\\TrackingService'])) {
            return $container->privates['App\\Service\\TrackingService'];
        }
        $b = ($container->privates['App\\Repository\\IncomeRepository'] ?? $container->load('getIncomeRepositoryService'));

        if (isset($container->privates['App\\Service\\TrackingService'])) {
            return $container->privates['App\\Service\\TrackingService'];
        }
        $c = ($container->privates['App\\Repository\\ExpenseRepository'] ?? $container->load('getExpenseRepositoryService'));

        if (isset($container->privates['App\\Service\\TrackingService'])) {
            return $container->privates['App\\Service\\TrackingService'];
        }
        $d = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\Service\\TrackingService'])) {
            return $container->privates['App\\Service\\TrackingService'];
        }

        return $container->privates['App\\Service\\TrackingService'] = new \App\Service\TrackingService($a, $b, $c, $d);
    }
}
